# SPDX-FileCopyrightText: gb-open-market-model contributors
#
# SPDX-License-Identifier: MIT

"""
COP profiles processing for heat pumps.

This script computes the ASHP and GSHP COP profiles weighted by population densities at urban and rural areas and saves it in CSV file format.
"""

import logging
from pathlib import Path

import pandas as pd
import xarray as xr

from scripts._helpers import configure_logging, set_scenario_config

logger = logging.getLogger(__name__)


def process_cop_profiles(
    cop_path: str,
    clustered_population_layout_path: str,
    district_heat_share_path: str,
    year: int,
) -> pd.DataFrame:
    """
    Process PyPSA-Eur COP profiles across urban and rural areas to obtain ASHP and GSHP profiles weighted by population

    Args:
        cop_path(str): Filepath to the COP profile generated by existing PyPSA-Eur rules
        clustered_population_layout_path(str): Filepath to the population density at each node generated by existing PyPSA-Eur rules
        district_heat_share_path(str): Filepath to district heat share at each country
        year(int): Modelling year

    Returns:
        pd.DataFrame : pandas dataframe containing the weighted average COP profiles
    """
    clustered_population_layout = pd.read_csv(
        clustered_population_layout_path, index_col="name"
    )

    district_heat_share_data = pd.read_csv(
        district_heat_share_path, index_col="country"
    )
    # Current data exists from 1990-2021, Choosing 2021 to project data for all future years
    if int(year) >= 1990 and int(year) <= 2021:
        district_heat_share = district_heat_share_data.loc[:, year]
    else:
        logger.warning(
            "District heat share data unavailable for the year {year}. The latest available data from 2021 is used"
        )
        district_heat_share = district_heat_share_data.loc[:, "2021"]

    # Map district heat share to population densities
    clustered_population_layout["urban central"] = (
        clustered_population_layout["ct"].map(district_heat_share)
        * clustered_population_layout["urban"]
    )
    clustered_population_layout["urban decentral"] = (
        1 - clustered_population_layout["ct"].map(district_heat_share)
    ) * clustered_population_layout["urban"]

    # Process COP profiles from PyPSA-Eur
    cop_profiles = (
        xr.open_dataset(cop_path)
        .to_dataframe()
        .squeeze(axis=1)
        .unstack(level=["heat_source", "heat_system"])
    )
    cop_profiles.reset_index().set_index(["name", "time"], inplace=True)

    # Calculate COP as a weighted average with population densities as the weight
    # ASHP - weighted average of COP across urban central, urban decentral and rural
    # GSHP - Present only at rural (so no averaging done)
    heat_source = ["air", "ground"]
    heat_system = ["urban central", "urban decentral", "rural"]

    cop_wt_avg = pd.DataFrame(index=cop_profiles.index)
    for source in heat_source:
        cop_profile_filter = cop_profiles[source]
        cop_wt_avg[source] = (
            cop_profile_filter * clustered_population_layout[heat_system]
        ).sum(axis=1)
        if source == "air":
            cop_wt_avg[source] /= clustered_population_layout["total"]
        else:
            cop_wt_avg[source] /= clustered_population_layout["rural"]

    # To match the naming convention in FES data
    cop_wt_avg.rename(columns={"air": "ASHP", "ground": "GSHP"}, inplace=True)

    return cop_wt_avg


if __name__ == "__main__":
    if "snakemake" not in globals():
        from scripts._helpers import mock_snakemake

        snakemake = mock_snakemake(Path(__file__).stem, clusters="clustered", year=2022)
    configure_logging(snakemake)
    set_scenario_config(snakemake)

    cop_profile = process_cop_profiles(
        cop_path=snakemake.input.cop_profile,
        clustered_population_layout_path=snakemake.input.clustered_pop_layout,
        district_heat_share_path=snakemake.input.district_heat_share,
        year=snakemake.params.year,
    )

    # Save the COP profiles
    cop_profile.to_csv(snakemake.output.csv)
    logger.info(f"ASHP & GSHP COP profile saved to {snakemake.output.csv}")
