# SPDX-FileCopyrightText: gb-dispatch-model contributors
#
# SPDX-License-Identifier: CC0-1.0

name: gb-model-extras
channels:
- conda-forge
- bioconda
dependencies:
- curl
- python-dotenv

- pip:
  - pdfplumber==0.9.0 # technically noarch but imagemagick dependency not available on Windows
