# SPDX-FileCopyrightText: Contributors to PyPSA-Eur <https://github.com/pypsa/pypsa-eur>
#
# SPDX-License-Identifier: CC0-1.0

name: pypsa-eur
channels:
- conda-forge
- bioconda
dependencies:
- python>=3.10
- pip

# Inhouse packages
- pypsa>=0.32.1
- atlite>=0.3
- linopy>=0.4.4
- powerplantmatching>=0.5.15

# Dependencies of the workflow itself
- curl
- numpy
- pandas>=2.1
- geopandas>=1
- xarray>=2024.03.0,<2025.07.0
- openpyxl
- python-dotenv

- pip:
  - pdfplumber==0.9.0 # technically noarch but imagemagick dependency not available on Windows
