# SPDX-FileCopyrightText: gb-dispatch-model contributors
#
# SPDX-License-Identifier: CC0-1.0

noa_sets:
- id: 0
  name: "East Anglia GREEN (AENC and ATNC)"   # any meaningful name
  noa_options:
  - AENC

- id: 1
  name: "North East Scotland (BBNC and BPNC)"
  noa_options:
  - BBNC
  - BPNC

- id: 2
  name: "North to South Scotland" # any meaningful name
  noa_options:
  - BDUP
