# SPDX-FileCopyrightText:  gb-open-market-model contributors
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  name: "GB"

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: overnight

scenario:
  clusters:
  - clustered
  - all
  opts:
  - ""
  sector_opts:
  - ""
  planning_horizons:
  - 2030

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries:
- "BE"
- "DK"
- "FR"
- "GB"
- "IE"
- "NL"
- "NO"

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  retrieve_databundle: true
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  focus_weights: {NL: 0.01, "NO": 0.01, BE: 0.01, DK: 0.01, IE: 0.02, FR: 0.03, GB: 0.91}
  mode: gb_shapes

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#solving
solving:
  options:
    load_shedding: false
  solver:
    name: gurobi
    options: gurobi-default

urls:
  gb-etys-boundaries: https://api.neso.energy/dataset/997f4820-1ad4-499b-b1fe-4b8d3d7fbc72/resource/e914fcec-1dc9-4f1f-97e7-59c0d9521bea/download/etys-boundary-gis-data-mar25.zip
  transmission-availability: https://www.neso.energy/document/211021/download
  fes-workbook: https://www.neso.energy/document/199971/download # FES 2021 workbook
  gsp-coordinates: https://api.neso.energy/dataset/963525d6-5d83-4448-a99c-663f1c76330a/resource/41fb4ca1-7b59-4fce-b480-b46682f346c9/download/fes2021_regional_breakdown_gsp_info.csv
  eur-supply-table: https://api.neso.energy/dataset/bd83ce0b-7b1e-4ff2-89e8-12d524c34d99/resource/6563801b-6da4-46e7-b147-3d81c0237779/download/fes2023_es2_v001.csv
target_crs: "EPSG:27700"

# Manual region merging configuration
region_operations:
  area_loss_tolerance_percent: 0.01 # percentage of area loss tolerated when splitting regions
  min_region_area: 1000000 # minimum area of a region in square meters (1 km²) for keeping it after splitting
  # Regions to split before merging
  splits:
  - region: 6
    type: "vertical"
    coordinate: -2.48
  - region: 5
    type: "vertical"
    coordinate: -1.93
  - region: 8
    type: "vertical"
    coordinate: -2.48
  - region: 46
    type: "horizontal"
    coordinate: 53.1

  # Groups of regions to merge together
  merge_groups:
  - id: 1
    merge: [1]
    TO: NGET
  - id: 2
    merge: [2, 3, 91, 92]
    TO: NGET
  - id: 3
    merge: [4, "5w"]
    TO: NGET
  - id: 4
    merge: [5e]
    TO: NGET
  - id: 5
    merge: ["6e", "6ws", 7, 9]
    TO: NGET
  - id: 6
    merge: [8e]
    TO: NGET
  - id: 7
    merge: [10, "6wn", 11, 12, "8w"]
    TO: NGET
  - id: 8
    merge: [13, 16, 17]
    TO: NGET
  - id: 9
    merge: [14, 15, 25, 26, 27, 28, 29, 30, 35, 36, 37, 38]
    TO: NGET
  - id: 10
    merge: [18, 19, 20, 21, 22, 23, 24, 31, 32, 33, 34, 94, 95, 96, 97, 98]
    TO: NGET
  - id: 11
    merge: [39, 99]
    TO: NGET
  - id: 12
    merge: [40, 44, 45]
    TO: NGET
  - id: 13
    merge: [42]
    TO: NGET
  - id: 14
    merge: [41, 43, "46s"]
    TO: NGET
  - id: 15
    merge: [46n]
    TO: NGET
  - id: 16
    merge: [47, 48, 49]
    TO: NGET
  - id: 17
    merge: [50]
    TO: NGET
  - id: 18
    merge: [51]
    TO: NGET
  - id: 19
    merge: [52, 53]
    TO: NGET
  - id: 20
    merge: [54, 55, 56]
    TO: NGET
  - id: 21
    merge: [57]
    TO: NGET

  - id: 22
    merge: [58]
    TO: SPTL
  - id: 23
    merge: [59]
    TO: SPTL

  - id: 24
    merge: [60]
    TO: SHETL
  - id: 25
    merge: [61, 64]
    TO: SHETL
  - id: 26
    merge: [62, 63, 86, 87, 88]
    TO: SHETL
  - id: 27
    merge: [65, 66, 67, 68, 69, 70, 71, 72, 73, 84, 85]
    TO: SHETL
  - id: 28
    merge: [74, 75, 76]
    TO: SHETL
  - id: 29
    merge: [77, 78, 79]
    TO: SHETL
  - id: 30
    merge: [80, 81, 82, 83]
    TO: SHETL
  - id: 31
    merge: [89]
    TO: SHETL
  - id: 32
    merge: [90]
    TO: SHETL
  - id: 33
    merge: [93]
    TO: SHETL

# Note: Set ENTSO_E_API_KEY in your .env file or environment variables
# Register at https://transparency.entsoe.eu/ to get API key
entsoe_unavailability:
  start_date: "2023-01-01"
  end_date: "2024-01-01"
  bidding_zones: ["GB"]  # Great Britain only
  business_types: ["planned", "forced"]  # planned maintenance and forced outages
  max_request_days: 7  # Maximum days per API request to avoid timeouts
  api_params:
    # UK bidding zone codes
    bidding_zones:
      GB: "10YGB----------A"  # Great Britain
    # Business types for outage classification
    business_types:
      planned: "A53"  # Planned maintenance
      forced: "A54"   # Forced unavailability (unplanned outage)
    # Document status codes
    doc_status:
      active: "A05"     # Active
      cancelled: "A09"  # Cancelled
      withdrawn: "A13"  # Withdrawn

fes-sheet-config:
  SV.34:
    usecols: "I:AN"
    skiprows: 5
    index_col: 0
    header: 0
    rename:
      index: scenario
      columns: year

  BB1:
    usecols: "A:C,E,H:AK" # Ignore columns: "Baseline (2020)", "Share of GSP" (empty), "DNO License Area"
    skiprows: 0
    index_col: [0, 1, 2, 3]
    header: 0
    rename:
      columns: year

  BB2:
    usecols: "A:E"
    skiprows: 2
    index_col: [0, 1, 3]
    header: 0
    rename:
      columns: Parameter

fes:
  year_range_incl: [2022, 2041] # 20-year period over which we will run the simulation
  default_set: PP
  gb:
    scenario: Leading The Way   # fes workbook
    carrier_mapping:
      # Mapping undertaken in different columns for different carriers
      Technology:
        Biomass & Energy Crops (including CHP): biomass
        CCGTs (non CHP): CCGT
        Coal: coal
        Geothermal: geothermal
        Hydro: ror # FIXME: should this be just "hydro?"
        Hydrogen fuelled generation: hydrogen  # FIXME: something else here?
        Marine: marine
        Non-renewable Engines (Diesel) (non CHP): oil
        Non-renewable Engines (Gas) (non CHP): gas
        Non-renewable CHP: gas
        Nuclear: nuclear
        OCGTs (non CHP): OCGT
        Offshore-Wind (off-Grid): offwind
        Renewable Engines (Landfill Gas, Sewage Gas, Biogas): biomass
        Solar Generation: solar
        Waste Incineration (including CHP): waste
      Technology Detail:
        Domestic Batteries (G98): battery
        Batteries: battery
        Pumped Hydro: PHS # FIXME: should this be just "hydro?"
        Offshore Wind: offwind
        Onshore Wind <1MW: onwind
        Onshore Wind >=1MW: onwind

    set_mapping:
      Technology:
        Biomass & Energy Crops (including CHP): CHP
        Waste Incineration (including CHP): CHP
        Non-renewable CHP: CHP
        Storage: Store
  eur:
    scenario: CT & LW    # "Leading the Way" equivalent in the NESO european supply table
    carrier_mapping:
      # Mapping undertaken in different columns for different carriers
      Type:
        Biomass: biomass
        Marine: marine
        Nuclear: nuclear
        Offshore Wind: offwind
        Onshore Wind: onwind
        Waste: waste
      SubType:
        CCS Biomass: biomass
        CCS Gas: gas
        CCGT: OCGT
        Gas CHP: CCGT
        OCGT: OCGT
        Gas Reciprocating Engines: gas
        Hydrogen: hydrogen # hydrogen-fueled turbine
        Fuel Oil: oil
        Battery: battery
        Pumped Hydro: PHS
      SubSubType:
        Coal: coal
        Coal CHP: coal
        IGCC: coal
        Lignite: lignite
        Lignite CHP: lignite
        Peat CHP: lignite
        Hydro: hydro
        Reservoir Hydro: hydro
        Reservoir Hydro with pumping: hydro
        Run-of-river Hydro: ror
        Small-Scale-Hydro: ror
        Geothermal: geothermal
        Solar PV: solar
        Solar CSP: csp

      ## unmapped
      # Other Renewables

    set_mapping:
      SubType:
        Biomass CHP: CHP
        Gas CHP: CHP
        Battery: Store
        Pumped Hydro: Store
      SubSubType:
        Coal CHP: CHP
        Lignite CHP: CHP
        Peat CHP: CHP
        Reservoir Hydro with pumping: Store
