# SPDX-FileCopyrightText: gb-dispatch-model contributors
#
# SPDX-License-Identifier: CC0-1.0

noa_options:
- id: AENC
  grouped_name: AENC_ATNC
  name: "A new 400 kV double circuit in north East Anglia"
    # detailed description
  description: "Construct a new 400 kV double circuit in north East Anglia to facilitate power transfer requirements across the relevant boundaries. Substation works are required to accommodate the new circuits."
  commissioning_year: 2027
    # details of individual components to change
  details:
  - name: 60km of new 400kV double circuit OHL between Norwich Main and Bramford substations.
    pypsa_operations:
    - action: add
      component_type: substation
      name: Norwich Main Substation     # OSM name
      voltage: 400     # provide voltage level in KV (TODO: do we need to define AC or DC?)
      carrier: AC
    - action: add     # TODO: think if we need to make addition of several substations in one action
      component_type: substation
      name: Bramford Substation
      voltage: 400
      carrier: AC
    - action: add
      component_type: line
      name: AENC_400kV_OHL_NorwichMain_Bramford
      from: Norwich Main Substation # TODO: maybe we call it fully from_substation and to_substation
      to: Bramford Substation
      voltage: 400
      length_km: 60
      circuits: 2
      carrier: AC # probably not needed, because it is AC for lines by default
  - name: 120km of new 400kV double circuit OHL between Bramford and Tilbury substations via a new connection substation to be located in the Tendring district
    pypsa_operations:
    - action: add
      component_type: substation
      name: Tilbury Substation
      voltage: 400
      carrier: AC
    - action: add
      component_type: substation
      name: Lawford Substation # new connection substation to be located in the Tendring district (based on provided map: https://norwichtotilburymap.nationalgrid.com/)
      voltage: 400
      carrier: AC
    - action: add
      component_type: line
      name: AENC_400kV_OHL_Bramford_Tendring_Lawford
      from: Bramford Substation
      to: Lawford Substation
      voltage: 400
      length_km: 60 # approximate assumption based on provided map
      circuits: 2
      carrier: AC
    - action: add
      component_type: line
      name: AENC_400kV_OHL_Tendring_Lawford_Tilbury
      from: Lawford Substation
      to: Tilbury Substation
      voltage: 400
      length_km: 60 # approximate assumption based on provided map
      circuits: 2
      carrier: AC
- id: BBNC
  grouped_name: BBNC_BPNC
  name: "Beauly - Blackhillock 400 kV double circuit addition"
  description: "Construct a new 400 kV double circuit between Beauly and Blackhillock. At both sites extend the 400 kV busbar arrangements to allow for the connection of two additional bays."
  commissioning_year: 2030
  # details of individual components to change
  details:
  - name: new 110km 400kV double circuit OHL between new Beauly 400kV substation and new Blackhillock 400kV substation
    pypsa_operations:
    - action: add
      component_type: substation
      name: Beauly Substation
      voltage: 400
      carrier: AC
    - action: add
      component_type: substation
      name: Blackhillock Substation
      voltage: 400
      carrier: AC
    - action: add
      component_type: line
      name: BBNC_400kV_OHL_Beauly_Blackhillock
      from: Beauly Substation
      to: Blackhillock Substation
      voltage: 400
      length_km: 110
      circuits: 2
      carrier: AC
- id: BPNC
  grouped_name: BBNC_BPNC
  name: Blackhillock - Peterhead 400 kV double circuit addition
  description: "Establish a new 400 kV double circuit overhead line from Peterhed to Blackhillock via New Deer. Peterhead and Blackhillock substations will require extension to accomodate termination of the new double circuit. This reinforcement is required as onshore works to faciliate the 2nd Eastern HVDC Link from Peterhead (NOA option reference E4L5)"
  commissioning_year: 2030
  # details of individual components to change
  details:
  - name: new 82 km 400kV double circuit OHL between new substation of Blackhillock, New Deer, and Peterhead substations
    pypsa_operations:
    - action: add
      component_type: substation
      name: New Deer Substation
      voltage: 400
      carrier: AC
    - action: add
      component_type: substation
      name: Peterhead Substation
      voltage: 400
      carrier: AC
    - action: add
      component_type: line
      name: BBNC_400kV_OHL_Blackhillock_NewDeer
      from: Blackhillock Substation
      to: New Deer Substation
      voltage: 400
      length_km: 41 # approximate assumption
      circuits: 2
      carrier: AC
    - action: add
      component_type: line
      name: BBNC_400kV_OHL_NewDeer_Peterhead
      from: New Deer Substation
      to: Peterhead Substation
      voltage: 400
      length_km: 41 # approximate assumption
      circuits: 2
      carrier: AC
  - name: new 132kV substation at Peterhead
    pypsa_operations:
    - action: add
      component_type: substation
      name: Peterhead Substation
      voltage: 132
      carrier: AC
