# SPDX-FileCopyrightText:  gb-open-market-model contributors
#
# SPDX-License-Identifier: CC0-1.0

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#run
run:
  name: "GB"

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#foresight
foresight: overnight

scenario:
  clusters:
  - clustered
  - all
  opts:
  - ""
  sector_opts:
  - ""
  planning_horizons:
  - 2030

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#countries
countries:
  - "BE"
  - "DK"
  - "FR"
  - "GB"
  - "IE"
  - "NL"
  - "NO"

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#enable
enable:
  retrieve: auto
  retrieve_databundle: true
  retrieve_cost_data: true
  build_cutout: false
  retrieve_cutout: true

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#clustering
clustering:
  focus_weights: {NL: 0.01, "NO": 0.01, BE: 0.01, DK: 0.01, IE: 0.02, FR: 0.03, GB: 0.91}
  mode: gb_shapes

# docs in https://pypsa-eur.readthedocs.io/en/latest/configuration.html#solving
solving:
  options:
    load_shedding: false
  solver:
    name: gurobi
    options: gurobi-default

urls:
  gb-etys-boundaries: https://api.neso.energy/dataset/997f4820-1ad4-499b-b1fe-4b8d3d7fbc72/resource/e914fcec-1dc9-4f1f-97e7-59c0d9521bea/download/etys-boundary-gis-data-mar25.zip
  transmission-availability: https://www.neso.energy/document/211021/download
  fes-workbook: https://www.neso.energy/document/199971/download # FES 2021 workbook
target_crs: "EPSG:27700"
area_loss_tolerance_percent: 0.01 # percentage of area loss tolerated when splitting regions
min_region_area: 1000000 # minimum area of a region in square meters (1 km²) for keeping it after splitting

# Manual region merging configuration
region_operations:
  # Regions to split before merging
  splits:
  - region: 6
    type: "vertical"
    coordinate: -2.48
  - region: 5
    type: "vertical"
    coordinate: -1.93
  - region: 8
    type: "vertical"
    coordinate: -2.48
  - region: 46
    type: "horizontal"
    coordinate: 53.1

  # Groups of regions to merge together
  merge_groups:
  - [61, 64]
  - [47, 48, 49]
  - [54, 55, 56]
  - [52, 53]
  - [41, 43, "46s"]
  - [77, 78, 79]
  - [40, 44, 45]
  - [13, 16, 17]
  - [80, 81, 82, 83]
  - [18, 19, 20, 21, 22, 23, 24, 31, 32, 33, 34, 94, 95, 96, 97, 98]
  - [2, 3, 91, 92]
  - [14, 15, 25, 26, 27, 28, 29, 30, 35, 36, 37, 38]
  - [62, 63, 86, 87, 88]
  - [65, 66, 67, 68, 69, 70, 71, 72, 73, 84, 85]
  - [10, "6wn", 11, 12, "8w"]
  - ["6e", "6ws", 7, 9]
  - [39, 99]
  - [74, 75, 76]
  - [4, "5w"]

# Note: Set ENTSO_E_API_KEY in your .env file or environment variables
# Register at https://transparency.entsoe.eu/ to get API key
entsoe_unavailability:
  start_date: "2023-01-01"
  end_date: "2024-01-01"
  bidding_zones: ["GB"]  # Great Britain only
  business_types: ["planned", "forced"]  # planned maintenance and forced outages
  max_request_days: 7  # Maximum days per API request to avoid timeouts
  api_params:
    # UK bidding zone codes
    bidding_zones:
      GB: "10YGB----------A"  # Great Britain
    # Business types for outage classification
    business_types:
      planned: "A53"  # Planned maintenance
      forced: "A54"   # Forced unavailability (unplanned outage)
    # Document status codes
    doc_status:
      active: "A05"     # Active
      cancelled: "A09"  # Cancelled
      withdrawn: "A13"  # Withdrawn

fes-sheet-config:
  SV.34:
    usecols: "I:AN"
    skiprows: 5
    index_col: 0
    header: 0
    rename:
      index: scenario
      columns: year

  BB1:
    usecols: "A:C,E,H:AK" # Ignore columns: "Baseline (2020)", "Share of GSP" (empty), "DNO License Area"
    skiprows: 0
    index_col: [0, 1, 2, 3]
    header: 0
    rename:
      columns: year

  # Annual H2 demand for industrial sector in GWh between 2021-2050
  CV.53:
    usecols: "O:BD"
    skiprows: 6
    index_col: 0
    header: 0
    rename:
      index: scenario
      columns: year

  # Annual H2 demand for commercial sector in GWh between 2021-2050
  CV.54:
    usecols: "O:BD"
    skiprows: 6
    index_col: 0
    header: 0
    rename:
      index: scenario
      columns: year

  # Annual H2 demand for home heating in TWh between 2021-2050
  CV.10:
    usecols: "M:AR"
    skiprows: 5
    index_col: 0
    header: 0
    rename:
      index: scenario
      columns: year

  # Annual road transport demand in TWh between 2021-2050
  CV.33:
    usecols: "M:AW"
    skiprows: 7
    index_col: 0
    header: 0
    rename:
      index: carrier
      columns: year

  # Annual H2 demand in TWh for 2050 only
  SV.12:
    usecols: "M:Q"
    skiprows: 5
    index_col: 0
    header: 0
    rename:
      index: H2_demand
      columns: scenario

  # Hourly dispatch profile for ASHP and H2 boilers in GWh for 1 day
  CV.21:
    usecols: "K:M"
    skiprows: 4
    index_col: 0
    header: 0
    rename:
      index: hour
