# SPDX-FileCopyrightText: gb-dispatch-model contributors
#
# SPDX-License-Identifier: CC0-1.0

noa_options:
- id: BKUP
  name: Upgrade the existing network to a higher voltage between Blackhillock and Kintore.
  description: "long description."
  commissioning_year: 2034
  details:
  - name: Upgrade the existing network to a higher voltage between Blackhillock and Kintore.
    pypsa_operations:
    - action: add
      component_type: substation
      names:
      - Blackhillock
      - Kintore
      voltage: 400
      carrier: AC
    - action: update
      component_type: line
      name: BKUP_275kV_to_400kV_OHL_Blackhillock_Kintore
      from: Blackhillock
      to: Kintore
      from_voltage: 275
      to_voltage: 400
      carrier: AC

- id: BTR2
  name: Upgrade the existing circuits between Brinsworth and Thorpe Marsh to allow for more capacity.
  description: "long description."
  commissioning_year: 2027
  details:
  - name: Upgrade the existing circuits between Brinsworth and Thorpe Marsh to allow for more capacity.
    pypsa_operations:
   - action: add
      component_type: substation
      names:
      - Brinsworth
      - Thorpe Marsh
      voltage: 400
      carrier: AC
    - action: update
      component_type: line
      name: BTR2_275kV_to_400kV_OHL_Brinsworth_ThorpeMarsh
      from: Brinsworth
      to: Thorpe Marsh
      from_voltage: 275
      to_voltage: 400
      carrier: AC

- id: CLN2
  name: New circuit across North West England
  description: "long description."
  commissioning_year: 2036
  details:
  - name: New circuit across North West England

- id: CMN3
  name: New circuit between South East Scotland and North West England.
  description: "long description."
  commissioning_year: 2033
  details:
  - name: New circuit between South East Scotland and North West England.

- id: CVUP
  name: Upgrade the existing network to a higher voltage between Clydes Mill and Strathaven.
  description: "long description."
  commissioning_year: 2031
  details:
  - name: Upgrade the existing network to a higher voltage between Clydes Mill and Strathaven.
    pypsa_operations:
    - action: update
      component_type: line
      name: CVUP_275kV_to_400kV_ClydesMill_Strathaven
      from: Clydes Mill
      to: Strathaven
      from_voltage: 275
      to_voltage: 400
      carrier: AC

- id: DCR4
  name: Replace the conductors on the existing circuits between Carrington and Daines with higher capacity conductors.
  description: "long description."
  commissioning_year: 2027
  details:
  - name: Replace the conductors on the existing circuits between Carrington and Daines with higher capacity conductors.
    pypsa_operations:
    - action: add
      component_type: line
      name: DCR4_275kV_to_400kV_Carrington_Daines
      from: Carrington
      to: Daines
      voltage: 400
      capacity: 100
      carrier: AC

- id: DSUP
  name: Establish further connection capacity between Dounreay, Banniskirk (Spittal), and Thurso.
  description: "long description."
  commissioning_year: 2034
  details:
  - name: Establish further connection capacity between Dounreay, Banniskirk (Spittal), and Thurso.
    pypsa_operations:
    - action: add
      component_type: substation
      names:
      - Dounreay
      - Banniskirk
      - Thurso
      voltage: 400
      carrier: AC
    - action: update
      component_type: line
      name: DSUP_275kV_to_400kV_Dounreay_Banniskirk
      from: Dounreay
      to: Banniskirk
      from_voltage: 275
      to_voltage: 400
      carrier: AC
    - action: update
      component_type: line
      name: CVUP_275kV_to_400kV_Banniskirk_Thurso
      from: Banniskirk
      to: Thurso
      from_voltage: 275
      to_voltage: 400
      carrier: AC

- id: E4L6
  name: Refine one of the proposed offshore HVDC link planned between Scotland and Eastern England with a third connection into Lincolnshire.
  description: "long description."
  commissioning_year: 2033
  details:
  - name: Refine one of the proposed offshore HVDC link planned between Scotland and Eastern England with a third connection into Lincolnshire.
    pypsa_operations:
    - action: add
      component_type: substation
      names:
      - Grimsby West
      - Walpole
      voltage: 400
      carrier: AC
    - action: add
      component_type: line
      name: E4L6_400kV_Banniskirk_Thurso
      from: Grimsby West
      to: Walpole
      voltage: 400
      carrier: AC
    - action: update
      component_type: line
      name: E4L6_275kV_to_400kV_Banniskirk_Thurso
      from: Grimsby West
      to: Walpole
      from_voltage: 275
      to_voltage: 400
      carrier: AC

- id: ECRE
  name: Replace the conductors on a short section of the existing circuit between Errochty and Clunie with higher capacity conductors.
  description: "long description."
  commissioning_year: 2029
  details:
  - name: Replace the conductors on a short section of the existing circuit between Errochty and Clunie with higher capacity conductors.
    pypsa_operations:
    - action: add
      component_type: line
      name: ECRE_400kV_Errochty_Clunie
      from: Errochty
      to: Clunieaa
      voltage: 400
      capacity: 100
      carrier: AC

- id: ECSC
  name: Installation of series compensation on the existing circuit between East Anglia Coastal Node and Tilbury.
  description: "long description."
  commissioning_year: 2027
  details:
  - name: Installation of series compensation on the existing circuit between East Anglia Coastal Node and Tilbury.
    pypsa_operations:
    - action: add
      component_type: line
      name: ECSC_400kV_EastAngliaCoastal_Tilbury
      from: East Anglia Coastal
      to: Tilbury
      voltage: 400
      capacity: 100
      carrier: AC

- id: EDN3
  name: Replace the conductors on the existing circuits between Brinsworth and Thorpe Marsh, Brinsworth and Chesterfield, and Chesterfield and Ratcliffe with higher capacity conductors.
  description: "long description."
  commissioning_year: 2032
  details:
  - name: Replace the conductors on the existing circuits between Brinsworth and Thorpe Marsh, Brinsworth and Chesterfield, and Chesterfield and Ratcliffe with higher capacity conductors.
    pypsa_operations:
    - action: add
      component_type: line
      name: EDN3_400kV_Brinsworth_ThorpeMarsh
      from: Brinsworth
      to: Thorpe Marsh
      voltage: 400
      capacity: 100
      carrier: AC
    - action: add
      component_type: line
      name: EDN3_400kV_Brinsworth_Chesterfield
      from: Brinsworth
      to: Chesterfield
      voltage: 400
      capacity: 100
      carrier: AC
    - action: add
      component_type: line
      name: EDN3_400kV_Chesterfield_Ratcliffe
      from: Chesterfield
      to: Ratcliffe
      voltage: 400
      capacity: 100
      carrier: AC

- id: ESCF
  name: Reconfigure the network between Stalybridge and Thorpe Marsh.
  description: "long description."
  commissioning_year: 2033
  details:
  - name: Reconfigure the network between Stalybridge and Thorpe Marsh.
    pypsa_operations:
    - action: add
      component_type: line
      name: ESCF_400kV_Stalybridge_ThorpeMarsh
      from: Stalybridge
      to: Thorpe Marsh
      voltage: 400
      capacity: 100
      carrier: AC

- id: ETRE
  name: Upgrade the existing circuits between Eggborough and Thorpe Marsh to allow for more capacity.
  description: "long description."
  commissioning_year: 2029
  details:
  - name: Upgrade the existing circuits between Eggborough and Thorpe Marsh to allow for more capacity.
    pypsa_operations:
    - action: add
      component_type: line
      name: ETRE_400kV_Eggborough_ThorpeMarsh
      from: Eggborough
      to: Thorpe Marsh
      voltage: 400
      capacity: 100
      carrier: AC

- id: FSU1
  name: Upgrade the existing network to a higher voltage between Harker and Stella West.
  description: "long description."
  commissioning_year: 2035
  details:
  - name: Upgrade the existing network to a higher voltage between Harker and Stella West.
    pypsa_operations:
    - action: add
      component_type: line
      name: FSU1_400kV_Harker_StellaWest
      from: Harker
      to: Stella West
      voltage: 400
      capacity: 100
      carrier: AC

- id: HGNC
  name: New circuit between Harburn and Gala North.
  description: "long description."
  commissioning_year: 2036
  details:
  - name: New circuit between Harburn and Gala North.
    pypsa_operations:
    - action: add
      component_type: line
      name: HGNC_400kV_Harburn_GalaNorth
      from: Harburn
      to: Gala North
      voltage: 400
      capacity: 100
      carrier: AC

- id: HNRE
  name: Replace the conductors on the existing circuits between Hawthorn Pit and Norton with higher capacity conductors.
  description: "long description."
  commissioning_year: 2029
  details:
  - name: Replace the conductors on the existing circuits between Hawthorn Pit and Norton with higher capacity conductors.
    pypsa_operations:
    - action: add
      component_type: line
      name: HNRE_400kV_HawthornPit_Norton
      from: Hawthorn Pit
      to: Norton
      voltage: 400
      capacity: 100
      carrier: AC

- id: LPDC
  name: New HVDC link between North West England and North Wales.
  description: "long description."
  commissioning_year: 2037
  details:
  - name: New HVDC link between North West England and North Wales.
    pypsa_operations:
    - action: add
      component_type: link
      name: LPDC_OHL_DC_WestEngland_NorthWales
      from:  West England
      to: North Wales
      capacity: 2000
      carrier: DC

- id: LRN6
  name: New transmission capacity between the South Lincolnshire, Cambridgeshire and North West Norfolk boundary to Hertfordshire.
  description: "long description."
  commissioning_year: 2034
  details:
  - name: 60km of new 400kV double circuit OHL between Norwich Main and Bramford substations.
    pypsa_operations:
    - action: add
      component_type: line
      name: LRN6_400kV_OHL_SouthLincolnshire_Cambridgeshire
      from: South Lincolnshire
      to: Cambridgeshire
      voltage: 400
      carrier: AC
    - action: add
      component_type: line
      name: LRN6_400kV_OHL_Cambridgeshire_NorthWestNorfolk
      from: Cambridgeshire
      to: North West Norfolk
      voltage: 400
      carrier: AC
